CUDA_VISIBLE_DEVICES=$1 python run_prun_moa.py \
    -tf \
    --epochs 200 \
    --batch-size 64 \
    --lr 0.01 \
    --trigger-path 'data/trigger_set/pics' \
    --emb-path 'data/trigger_set/emb_pics' \
    --key-type 'image' \
    --train-private \
    --use-trigger-as-passport \
    --arch $2 \
    --dataset $3 \
    --tl-dataset $4 \
    --norm-type $5 \
    --passport-config $6 \
    --exp-id $7 \
